[package]
name = "processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path="../common"}

[features]
m6502 = []
m6502x = ["m6502"]
w65 = []
gbz80 = []
m68k = []
z80 = []
