name: rustfmt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
    
      run: |
        rustup toolchain add beta --component rustfmt
        rustup default beta
        rustup update
        cargo fmt -- --check
    
